global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'financial-crime-unit-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['financial-crime-unit-service:8087']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'financial-crime-unit-service'

  - job_name: 'fcu-postgres'
    static_configs:
      - targets: ['fcu-db:5432']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'pg_.*'
        action: keep

  - job_name: 'fcu-redis'
    static_configs:
      - targets: ['fcu-cache:6379']
