apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://fcu-prometheus:9090
    isDefault: true
    editable: false
    
  - name: FCU PostgreSQL
    type: postgres
    url: fcu-db:5432
    database: csic_platform
    user: postgres
    password: postgres
    isDefault: false
    editable: true
    
  - name: FCU Redis
    type: redis
    url: fcu-cache:6379
    database: 0
    isDefault: false
    editable: true
