global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'national-identity-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['national-identity-service:8086']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'national-identity-service'

  - job_name: 'identity-postgres'
    static_configs:
      - targets: ['identity-db:5432']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'pg_.*'
        action: keep

  - job_name: 'identity-redis'
    static_configs:
      - targets: ['identity-cache:6379']
