# Grafana Datasource Configuration
# This file configures Grafana to connect to Prometheus for metrics visualization

apiVersion: 1

# List of data sources to delete
deleteDatasources:
  - name: Prometheus
    orgId: 1

# List of data sources to insert/update
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    password: ""
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    withCredentials: false
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
      httpMode: GET
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
      cacheTimeout: 60
    secureJsonData:
      tlsCACert: ""
      tlsClientCert: ""
      tlsClientKey: ""
    version: 1
    editable: true
