apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://identity-prometheus:9090
    isDefault: true
    editable: false
    
  - name: Identity PostgreSQL
    type: postgres
    url: identity-db:5432
    database: csic_platform
    user: postgres
    password: postgres
    isDefault: false
    editable: true
    
  - name: Identity Redis
    type: redis
    url: identity-cache:6379
    database: 0
    isDefault: false
    editable: true
